namespace FoodDrinkApp.Services;

/// <summary>
/// Central configuration for the mockapi.io REST API endpoint.
/// When <see cref="EndpointUrl"/> is empty, <see cref="FoodCatalogService"/>
/// uses only local fallback data, ensuring the app remains usable without network access.
/// </summary>
public static class MockApiConfig
{
    // Replace this with the Resource endpoint generated by mockapi.io.
    // Example: https://682xxxx.mockapi.io/api/v1/foods
    public const string EndpointUrl = "";

    public static bool IsConfigured => !string.IsNullOrWhiteSpace(EndpointUrl);
}
